### ISSUE TITLE
Inserir logo do lado esquerdo da página

### ISSUE THREAD

**Issue by royopa** [PHPTestFestBrasil/phptestfestbrasil.github.io#1]
Remover o ano 2008 da imagem e inserir o log do lado esquerdo superior da página.
https://raw.githubusercontent.com/PHPTestFestBrasil/PHPTestFest/master/testfest_small.png

**Comment by lflimeira** [comment]
@royopa, tudo bem? 

Eu coloquei o logo no lado esquerdo, no entanto acho que não ficou muito legal com o fundo roxo. Vê o que vc acha la no PR.

**Comment by lflimeira** [comment]
Tarefa realizada, e PR aceito. https://github.com/PHPTestFestBrasil/phptestfestbrasil.github.io/pull/7

**Comment by rogeriopradoj** [comment]
Fechando esta issue devido à tradução em português da página oficial estar sendo feita em https://phptestfest.org/pt-br/ .
