### ISSUE TITLE
Centralizar lista de interesse no evento

### ISSUE THREAD

**Issue by lflimeira** [PHPTestFestBrasil/phptestfestbrasil.github.io#10]
Foi discutido no slack, sobre centralizar as listas para levantamento de interesse que estão no link https://github.com/PHPTestFestBrasil/phptestfestbrasil.github.io/wiki#a%C3%A7%C3%B5es-j%C3%A1-acontecendo-nas-comunidades-brasileiras

Eu criei uma para SP, e o Paraná criou outra, o que acham de unificar essas listas e colocar a opção para colocar a cidade e o estado?

Dessa forma podemos fazer um levantamento mais efetivo e facilita a divulgação.

**Comment by fernandodebrando** [comment]
Sou do PHPRS, não chegamos a criar um lista de interesses aqui, mas sou a favor de centralizar e assim ter uma ideia de âmbito nacional dos interessados. No próximo dia 14/09 vamos realizar aqui um meetup mais introdutório/preparatório já que poucos conhecem, neste encontro queremos já formar orientadores e deixar os ambientes de testes prontos e testados para o evento em outubro. Assim também acho que pode facilitar na divulgação.

**Comment by rogeriopradoj** [comment]
Fechando esta issue devido à tradução em português da página oficial estar sendo feita em https://phptestfest.org/pt-br/ . Podemos continuar com as discussões na wiki, https://github.com/PHPTestFestBrasil/phptestfestbrasil.github.io/wiki
