### ISSUE TITLE
Diminuir o tamanho da imagem na página inicial

### ISSUE THREAD

**Issue by royopa** [PHPTestFestBrasil/phptestfestbrasil.github.io#2]
Ajustar o tamanho da imagem na página inicial:
http://web.archive.org/web/20110717203324im_/http://qa.php.net/gfx/testfest_big.png

**Comment by lflimeira** [comment]
Tarefa realizada, e PR aceito. https://github.com/PHPTestFestBrasil/phptestfestbrasil.github.io/pull/7

**Comment by royopa** [comment]
@lflimeira verdade, esse fundo roxo não ficou muito legal

**Comment by lflimeira** [comment]
@royopa, pois é o que vc acha que ficaria melhor, alterar a cor do background ou colocar um fundo branco no logo (acho que pode ficar meio grosseiro o fundo branco, mas é minha opinião rsrsrsr)?

**Comment by royopa** [comment]
@lflimeira o que acha de "darkblue" no background?

**Comment by lflimeira** [comment]
Humm acho que ficou melhor, mas ainda n ficou bom @royopa 

![image](https://user-images.githubusercontent.com/7549765/28416946-83e467a8-6d2c-11e7-85e7-d5c4aeefb906.png)

**Comment by lflimeira** [comment]
O que acha assim @royopa ?

![image](https://user-images.githubusercontent.com/7549765/28417079-0b9dee44-6d2d-11e7-9352-2ea51955c7a4.png)

**Comment by royopa** [comment]
@lflimeira  Gostei! Será quu teria como mexer um pouco no texto PHP TestFest Brasil2017! pra ficar mais perto do logo a esquerda?

**Comment by lflimeira** [comment]
@royopa Tem sim :)  Deixar ele centralizado?

**Comment by lflimeira** [comment]
@royopa Eu mandei a alteração.

**Comment by rogeriopradoj** [comment]
Fechando esta issue devido à tradução em português da página oficial estar sendo feita em https://phptestfest.org/pt-br/ .
